export { default as LanguageInfo } from './LanguagePercentage'
export { default as IconText } from './IconText'
export { default as AlignedText } from './AlignedText'
export { default as SocialMediaIcon } from './SocialMediaIcon'
export { default as KnowledgeCard } from './KnowledgeCard'
export { default as EducationCard } from './EducationCard'